import turtle
# creating canvas or turtle instance
myturtle = turtle.Turtle()
myturtle.penup()
myturtle.goto(50,75)
myturtle.pendown()
myturtle.forward(100)
myturtle.left(90)
myturtle.forward(100)
myturtle.left(90)
myturtle.forward(100)
myturtle.left(90)
myturtle.forward(100)
myturtle.left(90)
turtle.done()